### ISSUE TITLE
Unable to Login or Register 

### ISSUE THREAD

**Issue by SandeepVashishtha** [MananGandhi1810/online-chess#1]
**Describe the bug**
the login or register button is not working in website

**To Reproduce**
1. Go to website
2. enter username and password
3. click on login
4. nothing happen struck on the same page with any response

**Expected behavior**
user can login or register in the website

**Comment by MananGandhi1810** [comment]
Hey, the issue is because of the fact that I had turned off the server, because of it being dormant most of the time, and that it costed me my MS Azure credits to run. I have restarted the server now, and it should resume working within some time. Do leave a feedback after testing the application.

**Comment by SandeepVashishtha** [comment]
Thanks for letting me know! I'll test the application shortly and provide you with feedback once it's up and running again.

**Comment by SandeepVashishtha** [comment]
Confirmed! Login and registration are working perfectly.
